name: Build and deploy .NET Core application to Web App BSNTools
on:
  push:
    branches:
    - exp-pwa-standalone
permissions:
  id-token: write
  contents: read
env:
  AZURE_WEBAPP_NAME: BSNTools
  AZURE_WEBAPP_PACKAGE_PATH: BSNTools.Web\published
  CONFIGURATION: Debug
  DOTNET_CORE_VERSION: 11.0.x
  WORKING_DIRECTORY: BSNTools.Web
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-quality: preview
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"
    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Test
      run: dotnet test "${{ env.WORKING_DIRECTORY }}" --no-build
    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
    - name: Publish Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
  deploy:
    runs-on: windows-latest
    needs: build
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ vars.BSNTools_CLIENT_ID_30BA }}
        tenant-id: ${{ vars.BSNTools_TENANT_ID_30BA }}
        subscription-id: ${{ vars.BSNTools_SUBSCRIPTION_ID_30BA }}
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
